import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { VotingArea } from "@/components/VotingArea/VotingArea";
import { gql } from "@apollo/client";
import client from "@/data/apollo-client";
import { EmployeeDTO } from "@/data/data";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ employees }: { employees: EmployeeDTO[] }) {
  console.log(employees)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app" className={inter.className}>
        <Header />
        <main>
          <p className="description">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Natus
            distinctio, ipsum laboriosam optio beatae quis, ex harum, dolor
            molestiae aut quia quae quam quasi ipsa quos saepe dolores quaerat
            nisi!
          </p>
          <VotingArea employees={employees} />
        </main>
        <Footer />
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query Employees {
        employees {
          id
          firstName
          lastName
          email
          points
          image
        }
      }
    `,
  });

  return {
    props: { employees: data.employees },
  };
}
